export const GETPLOT_BOT_NAME = 'GetAplot Bot';
export const GETPLOT_FORUM = 'GETPLOT_FORUM';
export const CONNECTION = 'CONNECTION';
export const CONNECT_USER = 'CONNECT_USER';
export const CONNECT_USER_SUCCESS = 'CONNECT_USER_SUCCESS';
export const CONNECT_USER_ERROR = 'CONNECT_USER_ERROR';
export const DISCONNECT = 'DISCONNECT';
