export const JOIN_ROOM_FORUM = 'JOIN_ROOM_FORUM';
export const MESSAGE_CHAT_FORUM = 'MESSAGE_CHAT_FORUM';
export const GET_ROOM_USERS = 'GET_ROOM_USERS';
export const IS_TYPING = 'IS_TYPING';
export const LEAVE_FORUM = 'LEAVE_FORUM';
